# Generated by Django 3.2 on 2021-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=20)),
                ('Salary', models.IntegerField(max_length=3)),
                ('Location', models.CharField(max_length=10)),
            ],
        ),
    ]
