# Generated by Django 3.2.3 on 2021-06-23 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_category_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categorys',
        ),
    ]
