# Generated by Django 3.2.3 on 2021-06-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subcategory',
            new_name='subcategorys',
        ),
    ]
