# Generated by Django 3.2.3 on 2021-06-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_subcategory_subcategorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorys',
            name='status',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('UNBLOCK', 'Unblock')], default='BLOCK', max_length=20),
        ),
    ]
