# Generated by Django 3.2.3 on 2021-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_subcategorys_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('Subcategory_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=0)),
                ('Discount', models.IntegerField(default=0)),
                ('Discount_price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank='True', null='True', upload_to='images/image/')),
                ('Descreption', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('BLOCK', 'Block'), ('UNBLOCK', 'Unblock')], default='BLOCK', max_length=20)),
            ],
        ),
    ]
