# Generated by Django 3.2.3 on 2021-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Subcategory_name',
            field=models.IntegerField(default=0),
        ),
    ]
