# Generated by Django 3.2.3 on 2021-07-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_product_subcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Subcategory_name',
            new_name='Subcategory_ID',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category_ID',
        ),
    ]
