# Generated by Django 3.2.3 on 2021-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_auto_20210702_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank='True', null='True', upload_to=''),
        ),
    ]
