# Generated by Django 3.2.3 on 2021-07-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_ID',
            field=models.IntegerField(default=0),
        ),
    ]
