# Generated by Django 3.2.3 on 2021-07-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
