# Generated by Django 3.2.3 on 2021-06-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='udefinlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('gender', models.CharField(default='', max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=20)),
                ('cpassword', models.CharField(max_length=20)),
                ('postal_code', models.CharField(default='', max_length=100)),
                ('location', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
