# Generated by Django 3.2.3 on 2021-06-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udefinlogin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udefinlogin',
            name='cpassword',
        ),
    ]
