# Generated by Django 3.2.3 on 2021-06-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udefinlogin', '0002_remove_udefinlogin_cpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='udefinlogin',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='udefinlogin',
            old_name='lname',
            new_name='last_name',
        ),
    ]
