# Generated by Django 3.2.3 on 2021-06-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udefinlogin', '0003_auto_20210603_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udefinlogin',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
