# Generated by Django 3.2.3 on 2021-06-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udefinlogin', '0005_alter_udefinlogin_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udefinlogin',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
