# Generated by Django 3.2.3 on 2021-05-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlcrud', '0006_employee_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('BLOCK', 'Block'), ('UNBLOCK', 'Unblock')], default='BLOCK', max_length=20),
        ),
    ]
